#!/bin/bash
# 2007-07-17, Aurelio Jargas
#
# Generate the functions list, used in list.t2t

source _config.sh

out='_list.t2t'

echo > $out   # ho headers
echo "%%%%%%%%%%% DO NOT EDIT -- NÃO EDITE %%%%%%%%%%%" >> $out
echo "%%%%%%%%%%% Generated by $(basename $0) %%%%%%%%%%%" >> $out
echo >> $out

ZZCOR=0 ZZOFF= ZZDIR=$gitroot/zz $gitroot/funcoeszz zzajuda --lista |
	cat -n - |
	tr -s '\t ' ' ' |
	sed 's/^ *\([0-9]*\) \(zz[^ ]*\) \(.*\)/  |  \1  | \2 | \3/' >> $out

echo "$out done."
