#!/bin/bash
# 2011-04-30, Aurelio Jargas
# License: MIT

out='description.php'

cd $(dirname "$0") || exit 1

(
	# Using subshell to avoid chdir in top level execution
	cd ..
	source _config.sh
	
	echo '<?php'
	echo '// DO NOT EDIT! Generated by description.php.sh script.'
	echo '$description = array('
	ZZCOR=0 ZZOFF='' ZZDIR="$gitroot/zz/" "$gitroot"/funcoeszz zzajuda --lista |
		sed "
			s/'/\\\\'/g
			s/  */' => '/1
			s/.*/'&',/
		"
	echo ');'
	echo '?>'

) > "$out"

echo "$out done."
